language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - tip

install:
  - go get -t -v ./...
  - go get -v golang.org/x/tools/cmd/cover

script:
  - go test -v -coverprofile=coverage.txt -covermode=count ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
